### PR TITLE
Fix sm

### LINKED ISSUE #8: When new stages file loaded close list/ order was not working correctlly
app/stagemanger not working as expected.

### PR DESCRIPTION
**Pull request by lauraGgit**
Update the functionality to fix #8 (which is not totally working yet.) Also, reimplement some of the global scoped classthis to make class properties accessible to the methods even when they get called deeply in a promise.

Because of the class property access difficult, what gets stubbed in the test for closedUsedStages is the opposite of what is needed to actually run the method in the class.

### CODE REVIEW

File: app/stagemanager.js [hunk 1]
```diff
@@ -86,26 +86,35 @@ class StageManager extends MyTrello {
...
-        var stages = data[0].map(value => value['name']),
-            self = this;
+      var deferred = Q.defer(),
+          stages = data[0].map(value => value['name']),
+          closing = [];
 
         data[1].forEach(function(trelloList) {
+          var listDefer = Q.defer();
+          closing.push(listDefer.promise);
             if (!(stages.includes(trelloList.name))) {
```
Comment (mgwalker) [inline app/stagemanager.js]: If this conditional fails, then `listDefer` will never resolve or reject.  This could result in the main promise for the method also never resolving/rejecting.

File: app/stagemanager.js [hunk 2]
```diff
@@ -114,9 +123,10 @@ class StageManager extends MyTrello {
 
     closeList(listData, trelloListID) {
         var deferred = Q.defer();
-        if (!listData.length || listData.length) {
+        console.log(listData);
+        if (!listData.length || listData.length == 0) {
```
Comment (mgwalker) [inline app/stagemanager.js]: Similar to the above comment, if this conditional fails, the promise never resolves or rejects.

File: app/stagemanager.js [hunk 3]
```diff
@@ -86,26 +86,35 @@ class StageManager extends MyTrello {
...
-                .catch(deferred.reject);
-
+                    self.closeList(d, trelloList.id).then(listDefer.resolve);
+                }).fail(function(err){console.log(err.stack)})
+                .catch(listDefer.reject);
             };
         });
-      return deferred.promise;
+
+        Q.all(closing).then(function() {
```
Comment (mgwalker) [inline app/stagemanager.js]: I think you could replace from here down with just:

```javascript
return Q.all(all);
```

Since `Q.all()` returns a promise, this should be functionally equivalent to creating and resolving/rejecting your own promise.

File: app/stagemanager.js [hunk 4]
```diff
@@ -86,26 +86,35 @@ class StageManager extends MyTrello {
...
+          var listDefer = Q.defer();
+          closing.push(listDefer.promise);
             if (!(stages.includes(trelloList.name))) {
                 self.getListCards(trelloList.id)
                 .then(function(d) {
-                    self.closeList(d, trelloList.id).then(deferred.resolve);
-                })
-                .catch(deferred.reject);
-
+                    self.closeList(d, trelloList.id).then(listDefer.resolve);
```
Comment (mgwalker) [inline app/stagemanager.js]: This is just a preference, but I've taken to unwinding promises so I don't have nesting (which is the problem promises are supposed to solve).  So I think personally, I might have written this like:

```javascript
.then(function(d) {
  return self.closeList(d, trelloList.id);
})
.then(deferred.resolve)
.catch(deferred.reject);
```

File: app/stagemanager.js [hunk 5]
```diff
@@ -125,22 +135,42 @@ class StageManager extends MyTrello {
...
-                self.t.put(url, { value: position }, function(e, data) {
-                    if (e) throw e;
+                self.t.put(url, { value: position }, function(err, data) {
+                  if (err) stageDefer.reject(err);
+                  stageDefer.resolve();
                 });
                 position++;
             }
         });
+        promiseWaterfall(ordering).then(function() {
```
Comment (mgwalker) [inline app/stagemanager.js]: I'm not sure how `promiseWaterfall` is different from `Q.all()`?

Comment (lauraGgit) [inline app/stagemanager.js]: It is supposed to do it sequentially as opposed to just gating when they all resolve.

**Comment by lauraGgit** [comment]
Your additions look good to me, i will make the adjustments and then ask you to close.

File: app/stagemanager.js [hunk 6]
```diff
@@ -76,36 +76,34 @@ class StageManager extends MyTrello {
...
-      var deferred = Q.defer();
-        var stages = data[0].map(value => value['name']),
-            self = this;
+      var deferred = Q.defer(),
+          stages = data[0].map(value => value['name']),
+          closing = [];
 
         data[1].forEach(function(trelloList) {
             if (!(stages.includes(trelloList.name))) {
+              var listDefer = Q.defer();
```
Comment (mgwalker) [inline app/stagemanager.js]: I love this fix for the conditional thing!

**Comment by mgwalker** [comment]
Nice updates!  LGTM!  🚀
